---
    name: Molecule Test CI
    on: [push, pull_request]
    defaults:
        run:
            working-directory: lemp
            
    jobs:
      build:
        runs-on: ubuntu-latest
        strategy:
          max-parallel: 4
          matrix:
            python-version: ["3.9", "3.10"]
    
        steps:
          - uses: actions/checkout@v3

          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v3
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install dependencies
            run: |
              python3 -m pip install --upgrade pip
              python3 -m pip install pytest-testinfra molecule 'molecule-plugins[docker]' yamllint ansible-lint
          - name: Test with molecule
            run: 
              molecule test
            env:
                PY_COLORS: 1